services:
  db:
    image: postgres
    platform: linux/amd64
    restart: always
    container_name: backend-db
    volumes:
      - pg-volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USERNAME -d $POSTGRES_DB" ]
      interval: 5s
  ktor:
    image: rfm9300/ktor-central:latest
    pull_policy: always
    platform: linux/amd64
    container_name: backend-ktor
    volumes:
      - ./app/files:/app/files
      - ./keystore.jks:/app/keystore.jks
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy


volumes:
  pg-volume: {}