CREATE TABLE calendar_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    location VARCHAR(255),
    image_path VARCHAR(500),
    is_all_day BOOLEAN DEFAULT FALSE NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    created_by_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_calendar_event PRIMARY KEY (id)
);

ALTER TABLE calendar_event ADD CONSTRAINT FK_CALENDAR_EVENT_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES user_profile (id);

CREATE INDEX idx_calendar_event_date ON calendar_event(event_date);
CREATE INDEX idx_calendar_event_type ON calendar_event(event_type);
CREATE INDEX idx_calendar_created_by ON calendar_event(created_by_id);
