services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://auth-db:27017/auth_db
      - APP_JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      - auth-db
    networks:
      - auth-network

  auth-db:
    image: mongo:7.0.31
    container_name: auth-db
    command: mongod --bind_ip_all --wiredTigerCacheSizeGB 0.25
    restart: always
    stop_grace_period: 60s
    ports:
      - "27017:27017"
    volumes:
      - auth-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 }).ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  auth-db-data:
