ktor:
  application:
    modules:
      - example.com.ApplicationKt.module
  deployment:
    port: 8080
    # SSL configuration for Facebook Authentication
    #sslPort: 8443
    watch:
      - classes
      - resources
  development: $IS_PRODUCTION
  #security:
   # ssl:
    #  keyStore: "keystore.jks"
     # keyAlias: sampleAlias
      #keyStorePassword: password123
      #privateKeyPassword: password123


storage:
  user: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  name: $POSTGRES_DB
  host: $POSTGRES_HOST

jwt:
  domain: "http://0.0.0.0:8080"
  issuer: "http://0.0.0.0:8080"
  audience: "users"
  realm: "ktor-backend"
  secret: $JWT_SECRET

smtp:
  host: smtp.gmail.com
  port: 587
  username: abizaria@gmail.com
  password: $SMTP_PASSWORD
  from: abizaria@gmail.com
  production: $IS_PRODUCTION